---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: agentydragon@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          webhook:
            groupName: acme.syself.com
            solverName: powerdns
            config:
              host: powerdns-api.dns-system:8081
              apiKeySecretRef:
                name: powerdns-api-key
                key: powerdns_api_key
        selector:
          dnsNames:
            - "*.test-cluster.agentydragon.com"
      - http01:
          ingress:
            class: nginx
