apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-vault
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  path: ./k8s/authentik-blueprint/vault
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: vault
      namespace: flux-system
    - name: external-secrets-config
      namespace: flux-system
    - name: reflector
      namespace: flux-system
    - name: sso-secrets
      namespace: flux-system
