apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-oidc-auth
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/vault-oidc-auth"
  prune: true
  wait: true
  dependsOn:
    - name: vault # Wait for Vault instance to be ready
    - name: external-secrets-config # Required for ExternalSecret resources
  # Verify terraform resource is ready
  healthChecks:
    - apiVersion: infra.contrib.fluxcd.io/v1alpha2
      kind: Terraform
      name: vault-oidc-auth
      namespace: flux-system
