apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-matrix
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/authentik-blueprint/matrix"
  prune: true
  wait: true
  dependsOn:
    - name: matrix # Wait for matrix base app
      namespace: flux-system
    - name: authentik # Wait for authentik to be ready
      namespace: flux-system
    - name: external-secrets-config # Wait for ESO to be configured
      namespace: flux-system
