---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgAfCkpfMHoX72VPGs5S3Apx6FAaunNcq8SWgYT02LLGCIhSi4kM3kYpluVwkBid5EK9wctfiLmVCUKVBGLe/qWqsySaQmRb4inoLe1AYXc86V0PK1/swVuCcx53BprycYR9i/52eMBogEeinY86oRWWb0LE6lMaJD7K3YP3lYM/Sxu8AMEDTQislgDta2Dw+upkzfFRgT2f3vtddxe0jhdvYdpMAIiLOQ7BPfWUJVf6pvi2IONAtZNiBGwZ5zJ4NFOGO9nj94Sa/VnCuOzN59r6ETmf5EdBWqpj6n7Drl0gNOq5CmeIjfOfJN3/L14Z2ZfpIDJWHqbGd/Pwgds0VWFJxVmyPZysaKIK3X7iEm7eXE0vdyC2nDbZYKdFYniQJOw3VRFPVwJAtZZ7qbqRTGf896yFWylvHfvRdPxoOyEaLXbbI73jg2qmePo/EBppp9rX2uhpZxIKmjXaOYF2cXXQOHLN7P1LlqDLZ9kU4q5kNVg8abHyT4YWB85sjIMob+2Pg/UNAlZEsDm4fosnoZEYs64hVtt18G3NDZ+DL9daDvABuzTU8zXDxLfUIorCHqJuhrMV/0UnJkCYv2nZk9RQStw0ydzEkLjdLT0HVEHx4PY+oRySqyNQ5Mqv0cLATrtJOOKQXTmBM8F+SGD8os6od4x6/zTs633TkL3jk28Lik2sLugXo79n2SjyivW6F+N9dz4Pr9k+KE5dcM0bM05PVtBWXSXNfclGMu2RNydFw6uUdVf+Ao7oL4YA2dU2lwJN8h6NzklsjMQMbzvxka9EpRvcTEazh01Nl2cP/zKnWODT0CWmRoFtGWRiTbNwlsbSw4yNpivCZy2kVJOjUARxhAq3Zq2owCR74wNjUHCvt3y4kl8Xw9wxc724iXnd/bWQPY7X1hr/LJTkrpKLD0UbHLeM5/VfucXXP/yhpwbDUxUeDvHUDCB9sdcSwv/qj3I=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
