---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  interval: 24h
  url: oci://ghcr.io/sergelogvinov/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
spec:
  interval: 15m
  chart:
    spec:
      chart: proxmox-csi-plugin
      version: "0.2.x"
      sourceRef:
        kind: HelmRepository
        name: proxmox-csi
        namespace: csi-proxmox
  values:
    config:
      existingSecret: "proxmox-csi-plugin"
    
    storageClass:
      - name: "proxmox-csi"
        storage: "local-zfs"
        reclaimPolicy: "Delete"
        allowVolumeExpansion: true
        parameters:
          cache: "directsync"
          ssd: "true"
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
    
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
    
    node:
      enableTopology: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi