---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgAqL0RBgfWpB6Elu7pJzA6kNqoA4mbhvgEZ+xyXkN/Pz8PIaD77ycmM0DCYiKYv88dXCYR9pjkxLxizOv0Ko2nR+J5NS9MFOFEXumfXtDPg5rMlLlmOIYDxoVtTiH9GrHNepfIqlJ10/5S+zDSjeXtCd5iEM+8tZsMhUkoEObS58RyMBE4j1/ILkz8XLV3LgMKWHmg1aCnNmLfvznm/L9cFDnuL+MZoZ+KCi22/bLwhcNeclRDMihdR1uplnxWJK8G1m3fZfLTe70EiZAvYZ/28g2Ufm5sqJiI6HdB6r++eRmUqB/IYB6Kb3hdnmkn20OgthxwTzOiki852yUiBGPrZ2sNUdYGgYCZ+WaYobd22y2y9yWyTqsAOR0LM8yaeQtcIy/6vxGVaqkSImtumFEMEPLkTiwEOWNkuuzvYazOiTF1dbfQjfxkXx5dM44qVPC8rHqtseBPNd2FHQB/LtREVUL73WQKazKjHiozH8Tgctol0I1rNekJvDubLlWPBnuua4WRCh4t1Td8DVnLOi1qgEoT695LSDTp19soJtNUl9XkmbRzd3C8EfL9fx5bgbs7DmYsytAHKJH1h2Cgh8pU/DMrAisNkYBYN/3MvnBBrVOIE61+CqEPitbdbhTZDsVSJYdp+obWkqVUaHylGbQ7UDvFt60HJFQmHRbN3OYh6QFhbm7djKO4QdovM8wKjckIJi2DT7chVTRWSXqiqnOr78kJGR0zpgJLzxssS4MsbJTzdeUZKsWiLuc/LEqswOG6zaYRygLNHZQPbbrjr7OFnYy1eh0xOCB/SgeyM0VWIE3OFZOgn/AtQqHsd05y3cXO3ma78PjKL8J0YVRwFewhNPM/q0vJG5+FP/IRVT0y0Xili2IYJxqaAqBV1/NyPUOBh2XIDvoA9PVOe01to/nj3uCnFS1Den/aBRNFFu7SgMt1BF8sVLvgnx1FpSYLKMzs=
  template:
    metadata:
      name: proxmox-csi
      namespace: csi-proxmox
    type: Opaque
