apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-ca
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/cluster-ca"
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager-trust # Wait for trust-manager CRDs
      namespace: flux-system
