---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager-trust
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: cert-manager-trust
spec:
  interval: 30m
  chart:
    spec:
      chart: trust-manager
      version: "v0.14.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager-trust
  values:
    replicaCount: 1
