apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-webhook
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/cert-manager-webhook"
  prune: true
  wait: true
  dependsOn:
    - name: cert-manager
      namespace: flux-system
    - name: reflector
      namespace: flux-system
    - name: powerdns
      namespace: flux-system
