apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-config
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./k8s/authentik-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  dependsOn:
    - name: authentik # Wait for authentik to be ready before configuring SSO
      namespace: flux-system
    - name: vault-config # Wait for vault to be configured
      namespace: flux-system
