apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpakNDQVRDZ0F3SUJBZ0lSQUxiRjNXWjl3ZVZONnZZNUNiaCtkdzR3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEV4TURreU16SXhORFphRncwek5URXhNRGN5TXpJeApORFphTUJVeEV6QVJCZ05WQkFvVENtdDFZbVZ5Ym1WMFpYTXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVFzckVNSlNZUzU1Y0gvS0JPQm44YkZvajBiTXVZWkNqbUFDUUYvWmNEYkpDUk9OL0tlUldqZlMwWTEKdTZENWtmTlovQlFoeExidWRCYjlOc3dxZjNXT28yRXdYekFPQmdOVkhROEJBZjhFQkFNQ0FvUXdIUVlEVlIwbApCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPCkJCWUVGQ1FmbDZIWlFFMTRGb2w5bWpBbU9qWlhHNTUxTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDRzQrUnYKODlnUmt5UGRyVlBPWjMxK2NMTENYRk9tR1YzYXJVREVRTFkzc2dJZ0w4WHM1OHZkRU5iMWhRbmdVcm1GV2FjZgpJVDMzMEszWGRRRjhIb2RUbzgwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.0.0.11:6443
  name: talos-cluster
contexts:
- context:
    cluster: talos-cluster
    namespace: default
    user: admin@talos-cluster
  name: admin@talos-cluster
current-context: admin@talos-cluster
kind: Config
users:
- name: admin@talos-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJnekNDQVNxZ0F3SUJBZ0lRR3NzWXVkMnVnZHdnS1pRSit6TGtaekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNVEV4TWpBME5Ea3lNbG9YRFRJMk1URXhNakEwTkRregpNbG93S1RFWE1CVUdBMVVFQ2hNT2MzbHpkR1Z0T20xaGMzUmxjbk14RGpBTUJnTlZCQU1UQldGa2JXbHVNRmt3CkV3WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFWXFRSHFXRW1TYWVHRW15QW44bU1TYjI3YUs5ZVNqd2IKNVpuUWEyQmQ3ZVlGRWRSVWt6YnVjTENKcTgxa3JmTnVNOXdmQUo5NTlCd2FvenBuOHFHdDFLTklNRVl3RGdZRApWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01COEdBMVVkSXdRWU1CYUFGQ1FmCmw2SFpRRTE0Rm9sOW1qQW1PalpYRzU1MU1Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lGWmhjMU9QNjVIMjFUWXcKcTl2SkUydXdrbjQ2NFVCaWF0eVhlM3R6Zll4L0FpQUR4YU8rRW11bUVEQlN1YURjaExoNndQeUtwVnNFbStJUQorRFo3c3FEeTh3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUtYenJqQlA2cERTODdvaGNDNHg4cEZ1bkJ3emRKbkZEcVNnUTNDTjBmMGRvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWXFRSHFXRW1TYWVHRW15QW44bU1TYjI3YUs5ZVNqd2I1Wm5RYTJCZDdlWUZFZFJVa3pidQpjTENKcTgxa3JmTnVNOXdmQUo5NTlCd2FvenBuOHFHdDFBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
