---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/applications/harbor"
  prune: true
  wait: true
  dependsOn:
    - name: ingress-nginx
    - name: cert-manager
    - name: vault
    - name: external-secrets
    - name: authentik
