---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-secrets
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      key: sso/harbor
      property: admin-password
  - secretKey: oidc-client-secret
    remoteRef:
      key: sso/harbor
      property: client-secret