apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitea
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/applications/gitea"
  prune: true
  wait: true
  dependsOn:
    - name: ingress-nginx
      namespace: flux-system
    - name: cert-manager
      namespace: flux-system
    - name: vault
      namespace: flux-system
    - name: external-secrets-config
      namespace: flux-system
