---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-secrets
  namespace: gitea
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: gitea-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: sso/gitea
        property: admin-password
    - secretKey: oidc-client-secret
      remoteRef:
        key: sso/gitea
        property: client-secret
