apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-blueprint-harbor-provider
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/authentik-blueprint/harbor-provider"
  prune: true
  wait: true
  dependsOn:
    - name: authentik # Wait for Authentik to be ready
      namespace: flux-system
    - name: sso-secrets # Wait for Harbor client secret from Vault
      namespace: flux-system
