apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: powerdns
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/powerdns"
  prune: true
  wait: true
  dependsOn:
    - name: metallb-config # Wait for MetalLB + IPAddressPools
    - name: external-secrets-config # Wait for External Secrets ClusterSecretStore for bootstrap secret generation
    - name: reflector # Wait for Reflector to handle secret copying
  # Ensure MetalLB can assign VIP before creating LoadBalancer service
  healthChecks:
    - apiVersion: metallb.io/v1beta1
      kind: IPAddressPool
      name: dns-pool
      namespace: metallb-system
    # Verify PowerDNS own services are ready
    - apiVersion: v1
      kind: Service
      name: powerdns-api
      namespace: dns-system
    - apiVersion: v1
      kind: Endpoints
      name: powerdns-api
      namespace: dns-system
