---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cdwv-powerdns
  namespace: dns-system
spec:
  interval: 24h
  url: https://github.com/cdwv/powerdns-helm
  ref:
    branch: master
