---
apiVersion: v1
kind: ConfigMap
metadata:
  name: powerdns-schema
  namespace: dns-system
data:
  schema.sql: |
    PRAGMA foreign_keys = 1;

    CREATE TABLE domains (
      id                    INTEGER PRIMARY KEY,
      name                  VARCHAR(255) NOT NULL COLLATE NOCASE,
      master                VARCHAR(128) DEFAULT NULL,
      last_check            INTEGER DEFAULT NULL,
      type                  VARCHAR(8) NOT NULL,
      notified_serial       INTEGER DEFAULT NULL,
      account               VARCHAR(40) DEFAULT NULL,
      options               VARCHAR(65535) DEFAULT NULL,
      catalog               VARCHAR(255) DEFAULT NULL
    );

    CREATE UNIQUE INDEX name_index ON domains(name);
    CREATE INDEX catalog_idx ON domains(catalog);

    CREATE TABLE records (
      id                    INTEGER PRIMARY KEY,
      domain_id             INTEGER DEFAULT NULL,
      name                  VARCHAR(255) DEFAULT NULL,
      type                  VARCHAR(10) DEFAULT NULL,
      content               VARCHAR(65535) DEFAULT NULL,
      ttl                   INTEGER DEFAULT NULL,
      prio                  INTEGER DEFAULT NULL,
      disabled              BOOLEAN DEFAULT 0,
      ordername             VARCHAR(255),
      auth                  BOOLEAN DEFAULT 1,
      FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

    CREATE INDEX rec_name_index ON records(name);
    CREATE INDEX nametype_index ON records(name,type);
    CREATE INDEX domain_id ON records(domain_id);
    CREATE INDEX recordorder ON records (domain_id, ordername);

    CREATE TABLE supermasters (
      ip                    VARCHAR(64) NOT NULL,
      nameserver            VARCHAR(255) NOT NULL COLLATE NOCASE,
      account               VARCHAR(40) NOT NULL
    );

    CREATE UNIQUE INDEX ip_nameserver_pk ON supermasters(ip, nameserver);

    CREATE TABLE comments (
      id                    INTEGER PRIMARY KEY,
      domain_id             INTEGER NOT NULL,
      name                  VARCHAR(255) NOT NULL,
      type                  VARCHAR(10) NOT NULL,
      modified_at           INTEGER NOT NULL,
      account               VARCHAR(40) DEFAULT NULL,
      comment               VARCHAR(65535) NOT NULL,
      FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

    CREATE INDEX comments_domain_id_idx ON comments (domain_id);
    CREATE INDEX comments_name_type_idx ON comments (name, type);
    CREATE INDEX comments_order_idx ON comments (domain_id, modified_at);

    CREATE TABLE domainmetadata (
      id                    INTEGER PRIMARY KEY,
      domain_id             INTEGER NOT NULL,
      kind                  VARCHAR(32),
      content               TEXT,
      FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

    CREATE INDEX domainidmetaindex ON domainmetadata(domain_id);

    CREATE TABLE cryptokeys (
      id                    INTEGER PRIMARY KEY,
      domain_id             INTEGER NOT NULL,
      flags                 INTEGER NOT NULL,
      active                BOOLEAN,
      published             BOOLEAN DEFAULT 1,
      content               TEXT,
      FOREIGN KEY(domain_id) REFERENCES domains(id) ON DELETE CASCADE ON UPDATE CASCADE
    );

    CREATE INDEX domainidindex ON cryptokeys(domain_id);

    CREATE TABLE tsigkeys (
      id                    INTEGER PRIMARY KEY,
      name                  VARCHAR(255),
      algorithm             VARCHAR(50),
      secret                VARCHAR(255)
    );

    CREATE UNIQUE INDEX namealgoindex ON tsigkeys(name, algorithm);
