---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/infrastructure/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  # Ensure CRDs are fully established before proceeding
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: sealedsecrets.bitnami.com
      namespace: ""
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: terraforms.infra.contrib.fluxcd.io
      namespace: ""
