apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cilium/flux-kustomization.yaml
  - ../cert-manager/flux-kustomization.yaml
  - ../metallb/flux-kustomization.yaml
  - ../ingress-nginx/flux-kustomization.yaml
  - ../powerdns/flux-kustomization.yaml
  - core-kustomization.yaml
  - platform-kustomization.yaml
