apiVersion: v2
name: powerdns
description: A Helm chart for PowerDNS authoritative DNS server with modern secret management
type: application
version: 0.1.18
appVersion: "4.7.3"
keywords:
  - dns
  - powerdns
  - authoritative
home: https://www.powerdns.com/
sources:
  - https://github.com/PowerDNS/pdns
maintainers:
  - name: agentydragon
    email: agentydragon@gmail.com

dependencies:
  - name: mariadb
    version: "~23.2.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: mariadb.enabled
