apiVersion: v2
name: attic
description: Multi-tenant Nix Binary Cache
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - nix
  - cache
  - binary-cache
home: https://github.com/zhaofengli/attic
sources:
  - https://github.com/zhaofengli/attic
maintainers:
  - name: cluster-admin
dependencies:
  - name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
