apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-secret-store.yaml
  - external-secrets.yaml
  - vault-bootstrap-sealed.yaml
  - vault-release.yaml
  - ../sso-secrets.yaml
  - ../vault-config.yaml
