apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "powerdns.fullname" . }}-config
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
data:
  pdns.conf: |
{{- include "powerdns.config" . | nindent 4 }}