{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "powerdns.fullname" . }}-api-key
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Values.externalSecret.secretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{ .Values.powerdns.api.secretKey }}: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: powerdns-api-key-generator
{{- end }}