apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # SealedSecret will be added here after generation:
  # - authentik-bootstrap-sealed.yaml
  - authentik-token-secret.yaml
  - authentik-release.yaml
  - ../authentik-config.yaml