---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  wait: true
  dependsOn:
    - name: vault
      namespace: flux-system
    - name: external-secrets
      namespace: flux-system
