apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - bootstrap-external-secret.yaml
  - secret-key-external-secret.yaml
  - token-secret.yaml
  - config.yaml
  - sso-secrets.yaml
  - postgres-external-secret.yaml
