apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - tf-runner-rbac.yaml
  - bootstrap-sealed.yaml
  - helmrelease.yaml
  - token-secret.yaml
  - config.yaml
  - sso-secrets.yaml
