apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault-sso
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/sso/vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: vault
    - name: external-secrets
    - name: reflector
    - name: authentik-config
