apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./k8s/vault"
  prune: true
  wait: true
  dependsOn:
    - name: cilium # Vault needs networking to function
  # Verify Vault's own service is ready
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: vault
      namespace: vault
    - apiVersion: apps/v1
      kind: Deployment
      name: vault
      namespace: vault
