apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Bank-Vaults Vault instance (operator deployed separately)
  - rbac.yaml
  - instance.yaml
  - ingress.yaml
  # Note: Certificate is automatically created by cert-manager from ingress annotation
