apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Bank-Vaults operator and Vault instance
  - rbac.yaml
  - operator.yaml  
  - instance.yaml
  # Terraform configuration (existing)
  - config.yaml
