apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Bank-Vaults Vault instance (operator deployed separately)
  - rbac.yaml
  - instance.yaml
  # TLS certificates - internal only (self-signed for pod-to-pod)
  - internal-tls-issuer.yaml
  - internal-tls-certificate.yaml
# Note: ingress.yaml and certificate.yaml moved to separate vault-ingress kustomization
# to prevent external cert issues from blocking core Vault functionality
