apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-kustomization.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - config-flux-kustomization.yaml
  - metallb-config
