apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault # Contains vault core resources, managed via vault-flux-kustomization.yaml
  - authentik
  - tf-runner-rbac.yaml
  - sso-secrets.yaml
  - vault-config.yaml
  - authentik-config.yaml
  - services-config.yaml
  - powerdns
