apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault
  - authentik
  - tf-runner-rbac.yaml
  - sso-secrets.yaml
  - vault-config.yaml
  - authentik-config.yaml
  - harbor-oidc-config.yaml
  - gitea-oidc-config.yaml
  - matrix-oidc-config.yaml
